name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: rustup update
      run: rustup update
    - name: cargo build
      run: cargo build --verbose
    - name: cargo test
      run: cargo test --verbose

